ç# Root logger
rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = STDOUT

# Console Appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1} %X: %m%n

# Application logs
logger.app.name = com.yelpbatch
logger.app.level = INFO

# Suppress Spark internal logs
logger.spark.name = org.apache.spark
logger.spark.level = WARN

logger.spark_context.name = org.apache.spark.SparkContext
logger.spark_context.level = WARN

logger.spark_storage.name = org.apache.spark.storage
logger.spark_storage.level = WARN

logger.spark_sql.name = org.apache.spark.sql
logger.spark_sql.level = WARN

logger.spark_scheduler.name = org.apache.spark.scheduler
logger.spark_scheduler.level = WARN

logger.spark_memory.name = org.apache.spark.memory
logger.spark_memory.level = WARN

logger.spark_network.name = org.apache.spark.network
logger.spark_network.level = WARN

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN

logger.delta.name = io.delta
logger.delta.level = ERROR

logger.parquet.name = org.apache.parquet
logger.parquet.level = WARN

