# Application Configuration File

# Data Paths Configuration
paths {
  rawDir = "data/raw"
  bronzeDir = "data/bronze"
  silverDir = "data/silver"
  goldDir = "data/gold"

  bronze {
    review   = "data/bronze/review"
    tip      = "data/bronze/tip"
    business = "data/bronze/business"
    checkin  = "data/bronze/checkin"
    user     = "data/bronze/user"
  }
  silver {
    review  = "data/silver/review_snapshot"
    tip     = "data/silver/tip_snapshot"
    business = "data/silver/business_snapshot"
    checkin = "data/silver/checkin_snapshot"
    user    = "data/silver/user_snapshot"
  }
  gold {
    factReviewTipMetrics = "data/gold/fact_review_tip_metrics"
    businessPopularity   = "data/gold/business_popularity"
  }
}
# MongoDB configuration
mongodb {
  enabled = true
}

# PostgreSQL configuration
postgresql {
  enabled = true
}

# Data Processing Configuration
granularity {
  daily   = 0
  monthly = 2
}

# Data Optimization Configuration
optimize {
  partition = "period_month"
  zorder    = ["business_id"]
}

app {
  tables = "business,review,user,checkin,tip"
  writeMode = "append"
}

tuning {
  shufflePartitions = 64 # adjust based on data size and cluster resources
  maxPartitionBytes = "32m" # control lecture file sizes, avoid OOM errors
  sourcesPartitionOverwriteMode = "dynamic" # efficient Idempotence (only overwrite partitions with new data)
  legacyTimeParserPolicy = "LEGACY" # handle legacy timestamp formats
  executorHeartbeat = "60s" # prevent long-running tasks from being killed
  partitionOverwriteMode = "dynamic"
  log4jpath= "src/main/resources/log4j2.properties" # custom log4j2 configuration
}

delta.stats {
  numIndexedCols = 8 # increase for better performance on large tables
}

writer {
  maxRecordsPerFile = 200000 # Avoid heavy file sizes
}

# Spark Deploy Mode
spark {
  deployMode = "client"
}