# Application Configuration File

# Data Paths Configuration
paths {
  rawDir = "data/raw"
  bronzeDir = "data/bronze"
  silverDir = "data/silver"
  goldDir = "data/gold"

  bronze {
    review   = "data/bronze/review"
    tip      = "data/bronze/tip"
    business = "data/bronze/business"
    checkin  = "data/bronze/checkin"
    user     = "data/bronze/user"
  }
  silver {
    review  = "data/silver/review_snapshot"
    tip     = "data/silver/tip_snapshot"
    business = "data/silver/business_snapshot"
    checkin = "data/silver/checkin_snapshot"
    user    = "data/silver/user_snapshot"
  }
  gold {
    factReviewTipMetrics = "data/gold/fact_review_tip_metrics_wide"
  }
}
# MongoDB configuration
mongodb {
  enabled = false
  uri = "mongodb://localhost:27017"
  database = "yelpAcademicDatasets"
}

# Data Processing Configuration
granularity {
  daily   = 0
  monthly = 2
}

optimize {
  partition = "period_month"
  zorder    = ["business_id"]
}

app {
  tables = "business,review,user,checkin,tip"
  writeMode = "append"
}

tuning {
  shufflePartitions = 64
  maxPartitionBytes = "32m"
  soucesPartitionOverwriteMode = "dynamic"
  legacyTimeParserPolicy = "LEGACY"
  partitionOverwriteMode = "dynamic"
  log4jpath= "src/main/resources/log4j2.properties"
}

delta.stats {
  numIndexedCols = 8
}

user {
  slim = true
}

writer {
  maxRecordsPerFile = 200000
}