include "application.conf"

paths {
  rootDir = "s3a://your-bucket/yelp-data"  # or gs:// for GCS, abfss:// for Azure
  rawDir = ${paths.rootDir}"/raw"

  bronze {
    review   = ${paths.rootDir}"/bronze/review"
    tip      = ${paths.rootDir}"/bronze/tip"
    business = ${paths.rootDir}"/bronze/business"
    checkin  = ${paths.rootDir}"/bronze/checkin"
    user     = ${paths.rootDir}"/bronze/user"
  }
  silver {
    review   = ${paths.rootDir}"/silver/review_snapshot"
    tip      = ${paths.rootDir}"/silver/tip_snapshot"
    business = ${paths.rootDir}"/silver/business_snapshot"
    checkin  = ${paths.rootDir}"/silver/checkin_snapshot"
    user     = ${paths.rootDir}"/silver/user_snapshot"
  }
  gold {
    factReviewTipMetrics = ${paths.rootDir}"/gold/fact_review_tip_metrics"
    businessPopularity = ${paths.rootDir}"/gold/business_popularity"
  }
}

tuning {
  shufflePartitions = 200
  maxPartitionBytes = "128m"
}

# Spark Deploy Mode
spark {
  deployMode = "cluster"
}
