spark.jars.packages=io.delta:delta-spark_2.12:3.2.0,org.mongodb.spark:mongo-spark-connector_2.12:10.4.0
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.hadoop.fs.file.impl=org.apache.hadoop.fs.LocalFileSystem
spark.driver.extraJavaOptions=-Dlog4j.configurationFile=file:///opt/airflow/config/log4j2.properties
spark.executor.extraJavaOptions=-Dlog4j.configurationFile=file:///opt/airflow/config/log4j2.properties
